// -----------------------------------
// variables.js - GLOBAL VARIABLES:
// -----------------------------------

// Local Date
// returns simplified local date for USA (e.g. "02/05/23")
// DEV NOTE: This is at the top because vars here use localdate format
function localdate() {
    // get current date
    let d = new Date();  
    // set to 2-digit values   
    let opts = {            
        day: '2-digit',
        month: '2-digit',
        year: '2-digit'
    };
    // return the local date
    return d.toLocaleDateString("en-US", opts);
}

// verbose console logging? (shows extra info)
// if this is turned off the user will see instructions
// default is false
export const verbose = true;

// devmode
// TODO: make this work with localstorage instead
// makes it easier for developers to troubleshoot problems
// default is false
export var devmode = false;

// SOLACE App Engine (SAE) Metadata
export const metadata = '/sae/lib/json/metadata.json';

// SOLACE backup file name - a JSON file with .solace extension
export const solbackfile = `Data_Backup_${localdate()}.solace`;

// The root level of the web site (default = '/')
// useful, if you store your site in a sub-directory
export const basedir = '/sae/';

// name of the main target DIV (e.g. <main id="ui"></main>)
// this div ID will be used to write innerHTML data to
// this value is stored in localstorage by storage.js 
// this is the default value used during initialization
export var targdiv = 'ui';

// default app border color
// can be changed by other functions
// default is '#898989' (dark gray)
export const appcolor = '#898989';

// timeout delay (in milliseconds)
// speed up or slow down time between sequences using setTimeout() method
// default is 1000
export const delay = 1000;

// sessionStorage key names:
export const solsess = 'SOLACE';                // SOLACE Session

// localStorage key names:
export const aekey = 'SOLACE_App_Engine';		// SOLACE App Engine Metadata
export const cappkey = 'SAE_Current';			// Current app
export const lappkey = 'SAE_Last';				// Last-used app
export const histkey = 'SAE_App_History';	 	// App history (last 10 apps used)
export const datakey = 'SAE_Saved_Data';	 	// Saved user data (generated by SAE)
export const infokey = 'SAE_Saved_Info';	 	// Saved information (system and device-related info)
export const backupkey = 'SAE_Session_Bak';	    // SOLACE Session backup

// disable the browser back button?
// prevents issues caused by the end-user 
// default is true
export const disableback = true;
// TODO: get 'disableback' working with 'devmode'
// TODO: someday, get this to work with screen-readers, etc. and manager app history

// --------------------------------------------------------------------
// DEV USE: VARS FOR TESTING PURPOSES
// --------------------------------------------------------------------

// test log messages? shows all possible colored-tags
// requires 'verbose' to also be set to true
// default is false
export const logtest = false;

// flag for tracking import of JSON
// SAE starts with loggerLight... then, after the JSON
// with colored-tags has loaded, it switches to loggerFull = true
// this is the default value used during initialization
// default is false
export const loggerFull = false;