// -----------------------------------
// variables.js - GLOBAL VARIABLES:
// -----------------------------------

// The root level of the web site (default = '/')
// useful, if you store your site in a sub-directory
export const basedir = '/sae/';

// verbose console logging? (shows extra info)
// if this is turned off the user will see instructions
// default is false
export const verbose = true;

// devmode
// makes it easier for developers to troubleshoot problems
// default is false
export const devmode = false;

// default app border color
// can be changed by other functions
// default is '#898989' (dark gray)
export const appcolor = '#898989';

// timeout delay (in milliseconds)
// speed up or slow down time between timed sequences
// default is 1000
export const delay = 1000;

// sessionStorage key names:
export const solsess = 'SOLACE';                // SOLACE Session

// localStorage key names:
export const aekey = 'SOLACE_App_Engine';		// SOLACE App Engine Metadata
export const cappkey = 'SAE_Current';			// Current app
export const lappkey = 'SAE_Last';				// Last-used app
export const histkey = 'SAE_App_History';	 	// App history (last 10 apps used)
export const datakey = 'SAE_Saved_Data';	 	// Saved user data (generated by SAE)
export const infokey = 'SAE_Saved_Info';	 	// Saved information (system and device-related info)
export const backupkey = 'SAE_Session_Bak';	    // SOLACE Session backup

// SAE Metadata (JSON file)
export const metadata = '/sae/lib/json/metadata.json';

// TODO: get 'disableback' working with 'devmode'
// disable browser back button?
// prevents issues related to random back button presses
// default is true
export const disableback = true;

// --------------------------------------------------------------------
// DEV USE: VARS FOR TESTING OR FUNCTIONS UNDER CURRENT DEVELOPMENT
// --------------------------------------------------------------------

// test log messages? shows all possible colored-tags
// requires 'verbose' to also be set to true
// default is false
export const logtest = false;

// flag for tracking colored-tags import of JSON file
// false = full logger functionality is not ready yet
// SAE starts with loggerLight... then, after the JSON 
// file has loaded, switches to loggerFull = true
// default is false
export const loggerFull = true;